// demo-react/src/App.tsx
import React from 'react';
// @ts-ignore
import ReactHighcharts from 'react-highcharts';

// @ts-ignore
import { createLineChart, createBarChart, createPieChart, createDonutChart } from '@pxblue/highcharts';

// @ts-ignore
import * as PXBColors from '@pxblue/colors';

const mainConfig = {
   colors: [PXBColors.blue[900], PXBColors.blue[500], PXBColors.blue[200]]
};
const lineConfig = {
   colors: [PXBColors.blue[500], PXBColors.blue[200], PXBColors.blue[200]]
};

const App: React.FC = () => {
   return (
      <div>
         <div style={{height: '200px'}}>
            <ReactHighcharts config={createPieChart()}/>
         </div>
         <div style={{height: '300px'}}>
            <ReactHighcharts config={createDonutChart(mainConfig)}/>
         </div>
         <div style={{height: '400px'}}>
            <ReactHighcharts config={createLineChart(lineConfig)}/>
         </div>
         <div style={{height: '400px'}}>
            <ReactHighcharts config={createBarChart(mainConfig)}/>
         </div>
      </div>
   );
}

export default App;

// angular-demo/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import { Chart } from 'angular-highcharts';

import {
  createLineChart,
  createBarChart,
  createPieChart,
  createDonutChart
} from '@pxblue/highcharts';
import * as PXBColors from '@pxblue/colors';

const mainConfig = {
  colors: [PXBColors.blue[900], PXBColors.blue[500], PXBColors.blue[200]]
};

const lineConfig = {
  colors: [PXBColors.blue[500], PXBColors.blue[200], PXBColors.blue[200]]
};

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {

  line: Chart;
  pie: Chart;
  donut: Chart;
  bar: Chart;

  ngOnInit() {
    this.init();
  }

  init() {
    let piechart = new Chart(createPieChart());
      this.pie = piechart;
    let donutchart = new Chart(createDonutChart(mainConfig));
      this.donut = donutchart;
    let linechart = new Chart(createLineChart(lineConfig));
      this.line = linechart;
    let barchart = new Chart(createBarChart(mainConfig));
      this.bar = barchart;
  }
}

<div [chart]="pie" style="height: 200px"></div>
<div [chart]="donut" style="height: 300px"></div>
<div [chart]="line" style="height: 400px"></div>
<div [chart]="bar" style="height: 400px"></div>
